# primary=['asp/malfunctions_test.lp']
primary=['asp/graph/0_input.lp','asp/graph/1_path.lp','asp/graph/2_output.lp']
secondary=['asp/graph/3_malfunction.lp','asp/graph/2_output.lp']
#primary=['asp/test2.lp']
# primary=['asp/test.lp']
# secondary=[]
