primary = ["asp/incremental/primary.lp"]
secondary = ["asp/incremental/secondary.lp"]
# primary = ["asp/graph_reschedule/0_input.lp", "asp/graph_reschedule/1_path.lp", "asp/graph_reschedule/2_output.lp"]
# secondary = ["asp/graph_reschedule/1_path.lp", "asp/graph_reschedule/2_output.lp", "asp/graph_reschedule/3_malfunction.lp"]
# primary = ["asp/incremental/allinone.lp"]
# secondary = ["asp/incremental/allinone.lp"]